version: '3.9'
services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventuate
    command: --default-authentication-plugin=mysql_native_password

  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.8.0.RELEASE
    environment:
      EVENTUATELOCAL_CDC_READER_READER: MySqlBinlog
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: root
      EVENTUATELOCAL_CDC_DB_HISTORY_DATA_SOURCE_URL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka
