spring:
  datasource:
    url: jdbc:mysql://eventuate-mysql:3306/eventuate
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysqluser
    password: mysqlpw

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  cdc:
    reader: MySqlBinlog
    data-source-url: jdbc:mysql://eventuate-mysql:3306/eventuate
    db-user-name: mysqluser
    db-password: mysqlpw